---
# This is a basic workflow to help you get started with Actions

name: CI publish

# Controls when the workflow will run
on:
  workflow_run:
    workflows: [CI build]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially
# or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part
    # of the job
    steps:
      - name: Download artifact
        uses: actions/github-script@v6
        with:
          debug: false
          script: |
            artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            artifactId = artifacts.data.artifacts[0].id;
            result = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifactId,
              "zip"
              })
            console.log(result)
      - name: Display structure of downloaded files
        run: ls -R
      - name: Install node packages
        run: npm install moment
      - uses: actions/github-script@v6
        with:
          debug: false
          script: |
            const moment = require('moment')
            const fs = require('fs');
            tag_name = moment().format('YYYYMMDD-HHmmss');
            releaseInfo = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name});
            console.log(releaseInfo);
            releaseId = releaseInfo.data.id;
            releaseUrl = releaseInfo.data.upload_url;
            zipData = fs.readFileSync("demo.jar.zip");
            result = await github.request({
              method: "POST",
              url: releaseUrl,
              headers: {
                "content-type": "application/zip",
                },
              data: zipData,
              name: "packed.zip",
              label: "Target",
              });
            console.log(result);
